apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.Namespace}} 
  labels: {{ include "common.labels" . | nindent 6}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.Namespace}}
  labels: {{ include "common.selector" . | nindent 4}}
spec:
  replicas: {{ .Values.Deployment.Replicas}}
  template:
    metadata:
      name: {{ .Values.Namespace}}
      labels: {{ include "common.selector" . | nindent 8}}
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.Deployment.ClaimName}}
      containers:
        - name: {{ .Values.Deployment.Containers}}
          image: {{ .Values.Deployment.Images}}
          imagePullPolicy: IfNotPresent
          env: {{ include "common.secretkey" . | nindent 12}}
          livenessProbe: {{ include "common.livenessProbe" . | nindent 12}}
          readinessProbe: {{ include "common.readinessProbe" . | nindent 12}}
          resources: {{ include "common.resources" . | nindent 12}}
          volumeMounts:
            - mountPath: /data
              name: data
          command:
            - /bin/bash
            - -c
          args:
              - minio server /data --console-address :9090
      restartPolicy: Always
  selector:
    matchLabels: {{ include "common.labels" . | nindent 6}}
