Namespace: minio 

Deployment:
  Replicas: 1
  ClaimName: minio
  Containers: minio-dev 
  Images: quay.io/minio/minio:latest
Service:
  PortConsole: 9090
  PortS3: 9000
  NodePortConsole: 31002
  NodePortS3: 31003
  Type: NodePort
PVC:
  Storage: 10Gi
  storageClassName: longhorn-storage-delete

Ingress:
  Name: minio.prod.bangpdk.dev
  Host: minio.prod.bangpdk.dev
  Service: minio
  Port: 9090
IngressUpload:
  Name: minioupload.prod.bangpdk.dev
  Host: minioupload.prod.bangpdk.dev
  Service: minio
  Port: 9000
  